Active record query interface
matlex/thinknetika_test_guru pull request #4
Opened 2019-02-04 18:09 UTC by matlex

2019-02-05 06:05 UTC, psylone requested changes

2019-02-05 06:05 UTC, psylone commented on app/models/author.rb
> +class Author < ApplicationRecord
Отдельная модель для автора не нужна, тем более, что поля с именем и фамилием повторяются. Метод ассоциации `user.created_tests` может возвращать созданные данным пользователем тесты и наоборот `test.author`.

2019-02-05 06:05 UTC, psylone commented on app/models/test.rb
> +  has_many   :questions
По диаграмме у теста могут быть, а могут не быть вопросы, а у вопроса обязательно есть ответ. Стоит оставить какой-то один вариант. Чтобы не париться с валидациями, можно сделать необязательное наличие объекта.

2019-02-05 06:05 UTC, psylone commented on app/models/user.rb
>      Test.joins("JOIN passed_tests ON tests.id = passed_tests.test_id AND passed_tests.user_id = #{self.id}").where(level: level_name)
Используй метод ассоциации `tests`.

2019-02-05 06:05 UTC, psylone commented on db/migrate/20190204132907_add_author_ref_to_tests.rb
> +    add_reference :tests, :author, foreign_key: true
Однотипные мигарции можно собрать в одну.

2019-02-12 16:10 UTC, matlex commented on db/migrate/20190204132907_add_author_ref_to_tests.rb
> +    add_reference :tests, :author, foreign_key: true
ок, понял

2019-02-12 23:42 UTC, psylone approved these changes

2019-02-15 12:31 UTC, merged